AWSTemplateFormatVersion: '2010-09-09'
Resources:
  TodoCreateUser:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: Todo-CreateUser-POST
      Runtime: nodejs20.x
      Role: !GetAtt lambdaExecutionRole.Arn
      Handler: todo-task/dist/controller/todo-controller.createUserHandler
      Code:
        S3Bucket: todo-tasks
        S3Key: todo-task.zip

  TodoLoginUser:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: Todo-LoginUser-POST
      Runtime: nodejs20.x
      Role: !GetAtt lambdaExecutionRole.Arn
      Handler: todo-task/dist/controller/todo-controller.loginUserHandler
      Code:
        S3Bucket: todo-tasks
        S3Key: todo-task.zip

  TodoUsersGET:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: Todo-Users-GET 
      Runtime: nodejs20.x
      Role: !GetAtt lambdaExecutionRole.Arn
      Handler: todo-task/dist/controller/todo-controller.getUsersHandler
      Code:
        S3Bucket: todo-tasks
        S3Key: todo-task.zip

  TodoUpdateTask :
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: Todo-UpdateTask-UPDATE 
      Runtime: nodejs20.x
      Role: !GetAtt lambdaExecutionRole.Arn
      Handler: todo-task/dist/controller/todo-controller.updateTaskHandler
      Code:
        S3Bucket: todo-tasks
        S3Key: todo-task.zip  
  
  TodoDeleteTask:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: Todo-DeleteTask-DELETE
      Runtime: nodejs20.x
      Role: !GetAtt lambdaExecutionRole.Arn
      Handler: todo-task/dist/controller/todo-controller.deleteTaskHandler
      Code:
        S3Bucket: todo-tasks
        S3Key: todo-task.zip 
  
  lambdaExecutionRole:
    Type : AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'lambda.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: 'LambdaBasicExecution'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
  TodoApi:
    Type : AWS::ApiGateway::RestApi
    Properties :
      Name: TodoTaskApi
      Body :
        openapi: 3.0.0
        info:
          version: '1.0'
          title: Todo-task
          description: adding users and revewing the tasks in the list
        paths: 
          /createUser:
            post:
              description: creating user with list of task
              requestBody:
                required: true
                content:
                  application/vnd.api+json:
                    schema:
                      $ref: '#/components/schemas/Adduser'
              responses:
                "201":
                  description: user added successfully
                  content:
                    application/vnd.api+json:
                      schema:
                        $ref: '#/components/schemas/Adduser' 
                "400":
                  description: cannot add the user
                  content:
                    application/vnd.api+json:
                      schema:
                        $ref: '#/components/schemas/BadRequest'

              x-amazon-apigateway-integration:
                  uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${TodoCreateUser.Arn}/invocations"
                  passthroughBehavior: "when_no_match"
                  httpMethod: "POST"
                  type: "aws_proxy"
          /loginUser:
            post:
              description: creating user with list of task
              requestBody:
                required: true
                content:
                  application/vnd.api+json:
                    schema:
                      $ref: '#/components/schemas/Login'
              responses:
                "200":
                  description: Authorized successfully
                  content:
                    application/vnd.api+json:
                      schema:
                        type: object
                        properties:
                          token:
                            type: string
                            example: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c'
                          typeofToken: 
                            type: string
                            example: bearer
                          expiresIn: 
                            type: number
                            example: 6000 
                          scope: 
                            type: string
                            example: read admin
                            description: Authorization token 
                "401":
                  description: Unauthorized
                  content:
                    application/vnd.api+json:
                      schema:
                        $ref: '#/components/schemas/UnauthorizedError'
                "404":
                  description: user not found
                  content:
                    application/vnd.api+json:
                      schema:
                        $ref: '#/components/schemas/UserNotFound'

              x-amazon-apigateway-integration:
                  uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${TodoLoginUser.Arn}/invocations"
                  passthroughBehavior: "when_no_match"
                  httpMethod: "POST"
                  type: "aws_proxy"
          /getUsers/{userId}:
            get:
              description: Get all the users.
              responses:
                "200":
                  description: retrieved all users successfully
                  content:
                    application/vnd.api+json:
                      schema:
                        $ref: '#/components/schemas/GetUsers' 
                "400":
                  description: users details are not retrived
                  content:
                    application/vnd.api+json:
                      schema:
                        $ref: '#/components/schemas/BadRequest'

              x-amazon-apigateway-integration:
                  uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${TodoUsersGET.Arn}/invocations"
                  passthroughBehavior: "when_no_match"
                  httpMethod: "GET"
                  type: "aws_proxy"

          /update-task/{userId}:
            put:
              description: updating user task in the list.
              requestBody:
                required: true
                content:
                  application/vnd.api+json:
                    schema:
                      $ref: '#/components/schemas/UpdateTask'
              responses:
                "200":
                  description: updated user task successfully
                  content:
                    application/vnd.api+json:
                      schema:
                        $ref: '#/components/schemas/UpdateTask'
                "400":
                  description: cannot updated the user task
                  content:
                    application/vnd.api+json:
                      schema:
                        $ref: '#/components/schemas/BadRequest'
                 
              x-amazon-apigateway-integration:
                  uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${TodoUpdateTask.Arn}/invocations"
                  passthroughBehavior: "when_no_match"
                  httpMethod: "PUT"
                  type: "aws_proxy"

          /delete-task/{userId}:
            delete:
              description: deleting a task from the user tasks list.
              responses:
                "200":
                  description: deleted a task successfully
                  content:
                    application/vnd.api+json:
                      schema:
                        $ref: '#/components/schemas/UpdateTask'
                "400":
                  description: cannot delete task
                  content:
                    application/vnd.api+json:
                      schema:
                        $ref: '#/components/schemas/BadRequest'
              x-amazon-apigateway-integration:
                  uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${TodoDeleteTask.Arn}/invocations"
                  passthroughBehavior: "when_no_match"
                  httpMethod: "DELETE"
                  type: "aws_proxy"

        components:
          schemas:
            Adduser:
              type: object
              description: user    
              properties:
                userName:
                  type: string
                userId:
                  type: string
                tasks:
                  type: array
                  items:
                    type: object
                    properties:
                      taskId:
                        type: string
                      taskName:
                        type: string
                      status:
                        type: string
            Login:
              type: object
              description: login user
              properties:
                userId:
                  type: string
                password:
                  type: string
            GetUsers:
              type: object
              description: get all tasks
              properties:
                userName:
                  type: string
                userId:
                  type: string
                tasks:
                  type: array
                  items:
                    type: object
                    properties:
                      taskId:
                        type: string
                      taskName:
                        type: string
                      status:
                        type: string
            UpdateTask:
              type: object
              description: Update user task    
              properties:
                userId:
                  type: string
                taskId:
                  type: string 
                taskName:
                  type: string
                status:
                  type: string  
            BadRequest:
              type: object
              properties:
                errors:
                    type: array
                    items:
                      type: object
                      properties:
                        details:
                          type: string
                          example: 'BadRequest'
                        status:
                          type: integer
                          example: 400  
            UserNotFound:
              type: object
              properties:
                errors:
                    type: array
                    items:
                      type: object
                      properties:
                        details:
                          type: string
                          example: 'UserNotFound'
                        status:
                          type: integer
                          example: 404  
            UnauthorizedError:
              type: object
              properties:
                errors:
                    type: array
                    items:
                      type: object
                      properties:
                        details:
                          type: string
                          example: 'Unauthorized'
                        status:
                          type: integer
                          example: 401       
                                       
      Name : todoTask  
  LambdaInvokePermission1:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt TodoCreateUser.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${TodoApi}/*/*/*

  LambdaInvokePermission2:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt TodoLoginUser.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${TodoApi}/*/*/*


  LambdaInvokePermission3:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt TodoUsersGET.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${TodoApi}/*/*/*

  LambdaInvokePermission4:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt TodoUpdateTask.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${TodoApi}/*/*/*

  LambdaInvokePermission5:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt TodoDeleteTask.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${TodoApi}/*/*/*

  ApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref TodoApi

  ApiGatewayStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId: !Ref TodoApi
      DeploymentId: !Ref ApiGatewayDeployment
      StageName: todo

  Task:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "Todo"
      AttributeDefinitions:
        - AttributeName: "userId"
          AttributeType: "S"
      KeySchema: 
        - AttributeName: "userId"
          KeyType: "HASH"
      ProvisionedThroughput: 
        ReadCapacityUnits: "4"
        WriteCapacityUnits: "4"    
